apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-dev

resources:
  - ../../base
  - namespace.yaml

images:
  - name: app-image
    newName: 123456789012.dkr.ecr.us-east-1.amazonaws.com/demo-service
    newTag: bootstrap

patches:
  - path: configmap-patch.yaml
  - path: deployment-patch.yaml

commonLabels:
  environment: dev

